# Generated by Django 5.2.6 on 2026-01-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_wholesale_price_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='شركة الريادة', max_length=100, verbose_name='اسم اللوغو')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='رابط صورة اللوغو من ImgBB')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'لوغو',
                'verbose_name_plural': 'اللوغوهات',
            },
        ),
    ]
