# Generated by Django 5.2.6 on 2026-02-09 10:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_wholesale_price_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ انتهاء الخصم'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='السعر النهائي بعد الخصم (اختياري، إذا وضع يتم اعتماده بدلاً من مبلغ الخصم)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='السعر بعد الخصم'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_start',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ بدء الخصم'),
        ),
    ]
