# Generated by Django 5.2.6 on 2026-01-08 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logo',
            name='image_url',
            field=models.URLField(default='https://via.placeholder.com/200', verbose_name='رابط صورة اللوغو من ImgBB'),
        ),
    ]
