# Generated by Django 4.2.10 on 2026-04-24 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_discount_end_product_discount_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='شركة الريادة المتحدة', max_length=100, verbose_name='اسم الموقع')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/', verbose_name='اللوغو')),
                ('whatsapp_number', models.CharField(default='07834950300', max_length=20, verbose_name='رقم الواتساب')),
                ('telegram_username', models.CharField(default='07834950300', max_length=100, verbose_name='اسم مستخدم التيليجرام')),
                ('contact_phone', models.CharField(default='07834950300', max_length=20, verbose_name='رقم الاتصال')),
            ],
            options={
                'verbose_name': 'إعدادات الموقع',
                'verbose_name_plural': 'إعدادات الموقع',
            },
        ),
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='صورة الإعلان'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الثانية'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الثالثة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الرابعة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='الصورة الرئيسية'),
        ),
    ]
