upstream django_app {
    server web:8000;
}

upstream frontend_app {
    server frontend:80;
}

server {
    listen 80;
    server_name 167.86.98.95 localhost;

    client_max_body_size 100M;

    # Django backend (API and Admin)
    location ~ ^/(api|admin|i18n|accounts) {
        proxy_pass http://django_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    # Django static files
    location /static/ {
        alias /app/staticfiles/;
    }

    # Django media files
    location /media/ {
        alias /app/media/;
    }

    # Frontend (React app)
    location / {
        proxy_pass http://frontend_app;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}
