# Generated by Django 5.2.6 on 2026-01-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_governorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_wholesale',
            field=models.BooleanField(default=False, verbose_name='تاجر جملة'),
        ),
    ]
