# Generated by Django 5.2.6 on 2026-01-08 20:39

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_wholesale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='يمكنك استخدام الحروف العربية والإنجليزية والأرقام والشرطات السفلية', max_length=150, unique=True, validators=[users.validators.validate_username_arabic_allowed], verbose_name='اسم المستخدم'),
        ),
    ]
